on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'login to dockerhup'
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: ' Build Image '
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/javaapp .

      - name: 'Pushing image to dockerHup'
        run: docker push -t ${{ secrets.DOCKER_USERNAME }}/javaapp  

